name: Wildlife
favicon: null
layout_spectrum: 0.5683276033960283
typography_spectrum: 0.9256750969216228
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.06647947221063077
  lightness: 0.659833135548979
  saturation: 0.5829259417951107
  rhythmicContrast: 0.16168349888175726
purpose: []
